### ISSUE TITLE
Integrate metrics and alerting

### ISSUE THREAD

**Issue by eckelj** [rddl-network/REPs#9]

**Comment by eckelj** [comment]
The unconfirmed transactions should not be higher than 10 for 5 min

![Screenshot from 2023-02-27 14-14-29](https://user-images.githubusercontent.com/1703752/221573425-9a7624b2-c550-46b2-a02e-9d73d222bf75.png)

**Comment by jmastr** [comment]
<img width="1792" alt="Screenshot 2023-03-02 at 11 36 50" src="https://user-images.githubusercontent.com/11860038/222404608-402b1c83-31f4-4d13-a117-595ed8f82402.png">
